### PR TITLE
Fix for python/Ironpython 2

### PR DESCRIPTION
**Pull request by CyrilWaechter**
Quick fix for #4

### CODE REVIEW

**Comment by eirannejad** [comment]
Thanks @CyrilWaechter

**Comment by CyrilWaechter** [comment]
Thanks. If you don't mind also merge it into pyrevit repo. I need it to fix a reported issue in pyrevitmep.

**Comment by eirannejad** [comment]
Will do. Thanks for reminding me.

**Comment by eirannejad** [comment]
0.1.15 was added into https://github.com/eirannejad/pyRevit/commit/08eed9a33c442b87e26510531b2ba762f839302a

**Pull request merged**
